# Capstone Two: Preprocessing and Training Data Development

In the EDA portion of this investigation, I concluded that the best approach would be to issolate the status of the contracts by either approved loans or refused loans which the data i will now be working with.

### 1. Sourcing and loading

#### 1a. Import relevant libraries

In [1]:
#importing nessicaty packages
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#### 1b. Load the data

In [2]:
#importing the data frames created in the EDA notebook where the approved and refused contractes
#where seperated into two different DF and any missing data was dropped :)
dropped_na_approved = pd.read_csv('dropped_na_approved.csv')
dropped_na_refused = pd.read_csv('dropped_na_refused.csv')
#dropping the column 'unnamed: 0' because it has no relivance 
dropped_na_approved.drop('Unnamed: 0', axis = 1, inplace = True)
dropped_na_refused.drop('Unnamed: 0', axis = 1, inplace = True)

### 1c. checking for null values, minor data cleaning

In [3]:
print(dropped_na_approved.isna().sum())
print(dropped_na_refused.isna().sum())

SK_ID_PREV                0
SK_ID_CURR                0
NAME_CONTRACT_TYPE        0
AMT_ANNUITY               4
AMT_APPLICATION           0
AMT_CREDIT                0
AMT_GOODS_PRICE           0
NAME_CASH_LOAN_PURPOSE    0
NAME_CONTRACT_STATUS      0
DAYS_DECISION             0
NAME_PAYMENT_TYPE         0
CODE_REJECT_REASON        0
NAME_CLIENT_TYPE          0
NAME_GOODS_CATEGORY       0
NAME_PORTFOLIO            0
NAME_PRODUCT_TYPE         0
CHANNEL_TYPE              0
SELLERPLACE_AREA          0
NAME_SELLER_INDUSTRY      0
CNT_PAYMENT               4
NAME_YIELD_GROUP          0
PRODUCT_COMBINATION       0
dtype: int64
SK_ID_PREV                 0
SK_ID_CURR                 0
NAME_CONTRACT_TYPE         0
AMT_ANNUITY               40
AMT_APPLICATION            0
AMT_CREDIT                 0
AMT_GOODS_PRICE            0
NAME_CASH_LOAN_PURPOSE     0
NAME_CONTRACT_STATUS       0
DAYS_DECISION              0
NAME_PAYMENT_TYPE          0
CODE_REJECT_REASON         0
NAME_CLIENT_TYPE           0
NAME_GOODS_CATEGORY        0
NAME_PORTFOLIO             0
NAME_PRODUCT_TYPE          0
CHANNEL_TYPE               0
SELLERPLACE_AREA           0
NAME_SELLER_INDUSTRY       0
CNT_PAYMENT               40
NAME_YIELD_GROUP           0
PRODUCT_COMBINATION        0
dtype: int64

there is some missing data kept as 'XNA' which still remains after EDA so we will simply remove them from the data frames

In [4]:
refused_df = dropped_na_refused[dropped_na_refused['NAME_YIELD_GROUP'] != 'XNA'] 
approved_df = dropped_na_approved[dropped_na_approved['NAME_YIELD_GROUP'] != 'XNA']

### 2. Creating dummy vareables

Creating dummy variables for the object dtypes and bringing it all together

In [5]:
dfo_approved = approved_df.select_dtypes(include=['object']) #select object type columns
approved_df = pd.concat([approved_df.drop(dfo_approved, axis=1), pd.get_dummies(dfo_approved)], axis=1)

In [6]:
dfo_refused = refused_df.select_dtypes(include=['object']) #select object type columns
refused_df = pd.concat([refused_df.drop(dfo_refused, axis=1), pd.get_dummies(dfo_refused)], axis=1)

Making sure they where murged together successfully

In [7]:
approved_df

,SK_ID_PREV,SK_ID_CURR,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_GOODS_PRICE,DAYS_DECISION,SELLERPLACE_AREA,CNT_PAYMENT,NAME_CONTRACT_TYPE_Cash loans,...,NAME_YIELD_GROUP_high,NAME_YIELD_GROUP_low_action,NAME_YIELD_GROUP_low_normal,NAME_YIELD_GROUP_middle,PRODUCT_COMBINATION_Cash Street: high,PRODUCT_COMBINATION_Cash Street: low,PRODUCT_COMBINATION_Cash Street: middle,PRODUCT_COMBINATION_Cash X-Sell: high,PRODUCT_COMBINATION_Cash X-Sell: low,PRODUCT_COMBINATION_Cash X-Sell: middle
0,1383531,199383,23703.930,315000.0,340573.5,315000.0,-684,-1,18.0,1,...,0,0,1,0,0,0,0,0,1,0
1,2664403,163660,9804.285,67500.0,82611.0,67500.0,-766,-1,12.0,1,...,1,0,0,0,1,0,0,0,0,0
2,1912691,365415,5693.085,45000.0,47970.0,45000.0,-529,4,12.0,1,...,1,0,0,0,1,0,0,0,0,0
3,2627285,219469,23567.850,229500.0,241920.0,229500.0,-920,-1,12.0,1,...,0,0,1,0,0,0,0,0,1,0
4,2029849,380539,18982.935,90000.0,92970.0,90000.0,-611,57,6.0,1,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20251,2272689,227232,30839.175,135000.0,152082.0,135000.0,-755,3,6.0,1,...,1,0,0,0,1,0,0,0,0,0
20252,2126826,366227,30205.350,450000.0,491580.0,450000.0,-358,-1,24.0,1,...,0,0,0,1,0,0,1,0,0,0
20253,1551728,342089,14567.850,202500.0,202500.0,202500.0,-660,-1,30.0,1,...,1,0,0,0,1,0,0,0,0,0
20254,2737753,295861,25996.365,337500.0,384277.5,337500.0,-502,-1,36.0,1,...,1,0,0,0,1,0,0,0,0,0
20255,2459206,238591,19401.435,180000.0,243936.0,180000.0,-1833,100,24.0,1,...,1,0,0,0,1,0,0,0,0,0

In [12]:
refused_df.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'AMT_ANNUITY', 'AMT_APPLICATION',
       'AMT_CREDIT', 'AMT_GOODS_PRICE', 'DAYS_DECISION', 'SELLERPLACE_AREA',
       'CNT_PAYMENT', 'NAME_CONTRACT_TYPE_Cash loans',
       'NAME_CASH_LOAN_PURPOSE_Building a house or an annex',
       'NAME_CASH_LOAN_PURPOSE_Business development',
       'NAME_CASH_LOAN_PURPOSE_Buying a garage',
       'NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land',
       'NAME_CASH_LOAN_PURPOSE_Buying a home',
       'NAME_CASH_LOAN_PURPOSE_Buying a new car',
       'NAME_CASH_LOAN_PURPOSE_Buying a used car',
       'NAME_CASH_LOAN_PURPOSE_Car repairs',
       'NAME_CASH_LOAN_PURPOSE_Education',
       'NAME_CASH_LOAN_PURPOSE_Everyday expenses',
       'NAME_CASH_LOAN_PURPOSE_Furniture',
       'NAME_CASH_LOAN_PURPOSE_Gasification / water supply',
       'NAME_CASH_LOAN_PURPOSE_Hobby', 'NAME_CASH_LOAN_PURPOSE_Journey',
       'NAME_CASH_LOAN_PURPOSE_Medicine',
       'NAME_CASH_LOAN_PURPOSE_Money for a third person',
       'NAME_CASH_LOAN_PURPOSE_Payments on other loans',
       'NAME_CASH_LOAN_PURPOSE_Purchase of electronic equipment',
       'NAME_CASH_LOAN_PURPOSE_Refusal to name the goal',
       'NAME_CASH_LOAN_PURPOSE_Repairs', 'NAME_CASH_LOAN_PURPOSE_Urgent needs',
       'NAME_CASH_LOAN_PURPOSE_Wedding / gift / holiday',
       'NAME_CONTRACT_STATUS_Refused',
       'NAME_PAYMENT_TYPE_Cash through the bank',
       'NAME_PAYMENT_TYPE_Cashless from the account of the employer',
       'NAME_PAYMENT_TYPE_Non-cash from your account', 'NAME_PAYMENT_TYPE_XNA',
       'CODE_REJECT_REASON_HC', 'CODE_REJECT_REASON_LIMIT',
       'CODE_REJECT_REASON_SCO', 'CODE_REJECT_REASON_SCOFR',
       'CODE_REJECT_REASON_SYSTEM', 'CODE_REJECT_REASON_VERIF',
       'CODE_REJECT_REASON_XNA', 'NAME_CLIENT_TYPE_New',
       'NAME_CLIENT_TYPE_Refreshed', 'NAME_CLIENT_TYPE_Repeater',
       'NAME_CLIENT_TYPE_XNA', 'NAME_GOODS_CATEGORY_XNA',
       'NAME_PORTFOLIO_Cash', 'NAME_PRODUCT_TYPE_walk-in',
       'NAME_PRODUCT_TYPE_x-sell', 'CHANNEL_TYPE_AP+ (Cash loan)',
       'CHANNEL_TYPE_Channel of corporate sales',
       'CHANNEL_TYPE_Contact center', 'CHANNEL_TYPE_Country-wide',
       'CHANNEL_TYPE_Credit and cash offices', 'CHANNEL_TYPE_Regional / Local',
       'CHANNEL_TYPE_Stone', 'NAME_SELLER_INDUSTRY_Connectivity',
       'NAME_SELLER_INDUSTRY_Construction',
       'NAME_SELLER_INDUSTRY_Consumer electronics',
       'NAME_SELLER_INDUSTRY_Furniture', 'NAME_SELLER_INDUSTRY_Industry',
       'NAME_SELLER_INDUSTRY_MLM partners', 'NAME_SELLER_INDUSTRY_XNA',
       'NAME_YIELD_GROUP_high', 'NAME_YIELD_GROUP_low_action',
       'NAME_YIELD_GROUP_low_normal', 'NAME_YIELD_GROUP_middle',
       'PRODUCT_COMBINATION_Cash Street: high',
       'PRODUCT_COMBINATION_Cash Street: low',
       'PRODUCT_COMBINATION_Cash Street: middle',
       'PRODUCT_COMBINATION_Cash X-Sell: high',
       'PRODUCT_COMBINATION_Cash X-Sell: low',
       'PRODUCT_COMBINATION_Cash X-Sell: middle'],
      dtype='object')

### 3. Standardizing numerical data

In [14]:
scaler = StandardScaler() #initiallizing StandardScaler

#scaling the approved dataframe
scaled_approved = scaler.fit_transform(approved_df) #standardizing the approved data
                #turning the array into a dataframe again 
scaled_approved = pd.DataFrame(scaled_approved, columns = approved_df.columns)

#scaling the refused dataframe
scaled_refused = scaler.fit_transform(refused_df) #standardizing the refused data
                #turning the array into a datafreame again 
scaled_refused = pd.DataFrame(scaled_refused, columns = refused_df.columns)

In [17]:
#verifying that the dataframe was scaled correctly 
display(scaled_refused, scaled_approved)

,SK_ID_PREV,SK_ID_CURR,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_GOODS_PRICE,DAYS_DECISION,SELLERPLACE_AREA,CNT_PAYMENT,NAME_CONTRACT_TYPE_Cash loans,...,NAME_YIELD_GROUP_high,NAME_YIELD_GROUP_low_action,NAME_YIELD_GROUP_low_normal,NAME_YIELD_GROUP_middle,PRODUCT_COMBINATION_Cash Street: high,PRODUCT_COMBINATION_Cash Street: low,PRODUCT_COMBINATION_Cash Street: middle,PRODUCT_COMBINATION_Cash X-Sell: high,PRODUCT_COMBINATION_Cash X-Sell: low,PRODUCT_COMBINATION_Cash X-Sell: middle
0,-0.319651,-0.742508,0.242747,-0.410996,-0.384297,-0.410996,-0.543734,-0.070311,-0.607516,0.0,...,1.585864,-0.352845,-0.721078,-0.596911,1.587675,-0.906995,-0.595862,-0.021555,-0.038174,-0.026107
1,-1.477783,-0.770413,-1.239463,-0.927122,-0.958903,-0.927122,-0.123629,-0.015688,-0.936266,0.0,...,1.585864,-0.352845,-0.721078,-0.596911,1.587675,-0.906995,-0.595862,-0.021555,-0.038174,-0.026107
2,0.054955,0.272897,-0.912574,-0.609506,-0.602253,-0.609506,1.094035,-0.070311,0.049986,0.0,...,-0.630571,-0.352845,1.386813,-0.596911,-0.629852,1.102542,-0.595862,-0.021555,-0.038174,-0.026107
3,-0.144906,0.735526,0.712642,0.716542,0.681167,0.716542,0.673930,-0.070311,0.049986,0.0,...,-0.630571,-0.352845,1.386813,-0.596911,-0.629852,1.102542,-0.595862,-0.021555,-0.038174,-0.026107
4,1.593304,-1.344806,-0.877105,-0.601565,-0.549336,-0.601565,1.051385,-0.070311,0.049986,0.0,...,-0.630571,2.834106,-0.721078,-0.596911,-0.629852,1.102542,-0.595862,-0.021555,-0.038174,-0.026107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32294,-1.129077,-0.808447,0.564204,0.581555,0.419350,0.581555,0.356186,-0.070311,0.707487,0.0,...,-0.630571,-0.352845,-0.721078,1.675291,-0.629852,-0.906995,1.678242,-0.021555,-0.038174,-0.026107
32295,0.963714,0.318858,1.032832,0.740363,0.751535,0.740363,0.130140,-0.070311,0.707487,0.0,...,-0.630571,-0.352845,-0.721078,1.675291,-0.629852,-0.906995,1.678242,-0.021555,-0.038174,-0.026107
32296,-0.792875,0.019291,-0.488317,-0.617446,-0.622780,-0.617446,0.354053,-0.070311,-0.278765,0.0,...,1.585864,-0.352845,-0.721078,-0.596911,1.587675,-0.906995,-0.595862,-0.021555,-0.038174,-0.026107
32297,0.422203,0.643788,-0.338718,-0.530102,-0.530486,-0.530102,0.164260,-0.070311,0.049986,0.0,...,1.585864,-0.352845,-0.721078,-0.596911,1.587675,-0.906995,-0.595862,-0.021555,-0.038174,-0.026107
32298,1.633524,1.399950,1.465538,-0.212485,-0.178591,-0.212485,-0.204664,-0.070311,-1.265017,0.0,...,-0.630571,-0.352845,-0.721078,1.675291,-0.629852,-0.906995,1.678242,-0.021555,-0.038174,-0.026107

,SK_ID_PREV,SK_ID_CURR,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_GOODS_PRICE,DAYS_DECISION,SELLERPLACE_AREA,CNT_PAYMENT,NAME_CONTRACT_TYPE_Cash loans,...,NAME_YIELD_GROUP_high,NAME_YIELD_GROUP_low_action,NAME_YIELD_GROUP_low_normal,NAME_YIELD_GROUP_middle,PRODUCT_COMBINATION_Cash Street: high,PRODUCT_COMBINATION_Cash Street: low,PRODUCT_COMBINATION_Cash Street: middle,PRODUCT_COMBINATION_Cash X-Sell: high,PRODUCT_COMBINATION_Cash X-Sell: low,PRODUCT_COMBINATION_Cash X-Sell: middle
0,-0.977879,-0.769959,0.003715,0.002835,-0.036604,0.002835,0.140433,-0.084992,-0.349348,0.0,...,-1.134263,-0.164882,2.313132,-0.582596,-1.122167,-0.455114,-0.558035,-0.07288,8.944719,-0.127309
1,1.424655,-1.115503,-0.886097,-0.758514,-0.763827,-0.758514,-0.015795,-0.084992,-0.769454,0.0,...,0.881630,-0.164882,-0.432314,-0.582596,0.891133,-0.455114,-0.558035,-0.07288,-0.111798,-0.127309
2,0.014667,0.836047,-1.149284,-0.827728,-0.861484,-0.827728,0.435743,-0.053667,-0.769454,0.0,...,0.881630,-0.164882,-0.432314,-0.582596,0.891133,-0.455114,-0.558035,-0.07288,-0.111798,-0.127309
3,1.355032,-0.575670,-0.004996,-0.260177,-0.314718,-0.260177,-0.309200,-0.084992,-0.769454,0.0,...,-1.134263,-0.164882,2.313132,-0.582596,-1.122167,-0.455114,-0.558035,-0.07288,8.944719,-0.127309
4,0.234421,0.982340,-0.298508,-0.689301,-0.734624,-0.689301,0.279515,0.278378,-1.189560,0.0,...,0.881630,-0.164882,-0.432314,-0.582596,0.891133,-0.455114,-0.558035,-0.07288,-0.111798,-0.127309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20247,0.689916,-0.500579,0.460492,-0.550874,-0.567981,-0.550874,0.005162,-0.059932,-1.189560,0.0,...,0.881630,-0.164882,-0.432314,-0.582596,0.891133,-0.455114,-0.558035,-0.07288,-0.111798,-0.127309
20248,0.416321,0.843901,0.419916,0.418116,0.389099,0.418116,0.761537,-0.084992,0.070757,0.0,...,-1.134263,-0.164882,-0.432314,1.716456,-1.122167,-0.455114,1.792002,-0.07288,-0.111798,-0.127309
20249,-0.662391,0.610418,-0.581148,-0.343233,-0.425848,-0.343233,0.186159,-0.084992,0.490863,0.0,...,0.881630,-0.164882,-0.432314,-0.582596,0.891133,-0.455114,-0.558035,-0.07288,-0.111798,-0.127309
20250,1.562237,0.163260,0.150470,0.072048,0.086602,0.072048,0.487184,-0.084992,0.910969,0.0,...,0.881630,-0.164882,-0.432314,-0.582596,0.891133,-0.455114,-0.558035,-0.07288,-0.111798,-0.127309
20251,1.039766,-0.390705,-0.271717,-0.412446,-0.309035,-0.412446,-2.048671,0.547773,0.070757,0.0,...,0.881630,-0.164882,-0.432314,-0.582596,0.891133,-0.455114,-0.558035,-0.07288,-0.111798,-0.127309

### 4. splitting data into training and testing sets

In [16]:
x = scaled_approved['AMT_APPLICATION'] #choosing x-values
y = scaled_approved['AMT_APPLICATION']#choosing y-values
#the 'a' indicates these x's and y's are for the approved DF
Xa_train, Xa_test, ya_train, ya_test = train_test_split(x, y, test_size = 0.25, random_state = 125)

we have now split the data into 75% teaining set and 25% testing set for the approved loans. we just need to do the same for the refused loans

In [18]:
x = scaled_refused['AMT_APPLICATION'] #choosing x-values
y = scaled_refused['AMT_APPLICATION']#choosing y-values
Xr_train, Xr_test, yr_train, yr_test = train_test_split(x, y, test_size = 0.25, random_state = 125)

All the data is now been processed, standardized and is ready to be used to develop a model